import type { Dictionary } from './data'
import type { GameLanguage } from './types'

export const languageDictionaryExtensions: Record<Exclude<GameLanguage, 'pl'>, Dictionary> = {
  en: {
    country: { A:['Austria','Albania'],B:['Bulgaria','Bahamas'],C:['Croatia','Cuba','Cyprus'],D:['Dominican Republic'],E:['Ecuador','Ethiopia'],G:['Ghana','Georgia'],H:['Honduras'],I:['Iceland','Indonesia','Iran','Israel'],J:['Jordan'],K:['Kazakhstan','Kuwait'],L:['Lithuania','Luxembourg'],M:['Morocco','Malaysia'],N:['Netherlands','New Zealand','Nigeria'],P:['Peru','Pakistan'],S:['Switzerland','Singapore','South Africa'],T:['Tanzania'],U:['United Kingdom','United States','Uruguay'],V:['Venezuela'],W:['Wales'] },
    city: { A:['Ankara','Atlanta'],B:['Barcelona','Budapest'],C:['Copenhagen','Cambridge'],D:['Dallas','Delhi'],E:['Eindhoven','Exeter'],F:['Fukuoka'],G:['Genoa','Guangzhou'],H:['Hong Kong','Havana'],I:['Innsbruck'],J:['Jerusalem','Johannesburg'],K:['Kuala Lumpur','Katowice'],L:['Liverpool','Los Angeles'],M:['Manchester','Montreal'],N:['Nairobi','Nice'],O:['Ottawa','Orlando'],P:['Porto','Philadelphia'],R:['Rotterdam','Reykjavik'],S:['Stockholm','Singapore'],T:['Tallinn','Taipei'],U:['Uppsala'],V:['Valencia','Vancouver'],W:['Washington','Wroclaw'],Y:['Yokohama'],Z:['Zagreb'] },
    name: { A:['Amelia','Arthur'],B:['Bella','Brian'],C:['Charlotte','Christopher'],D:['David','Daisy'],E:['Emma','Ethan'],F:['Freya','Felix'],G:['Gabriel','Georgia'],H:['Hannah','Harvey'],I:['Isabella','Ian'],J:['Jessica','Joseph'],K:['Katherine','Kenneth'],L:['Laura','Lucas'],M:['Mia','Matthew'],N:['Nicole','Nathan'],O:['Oliver','Ophelia'],P:['Peter','Penelope'],R:['Rachel','Ryan'],S:['Sophie','Steven'],T:['Theo','Theresa'],U:['Uma','Uri'],V:['Vanessa','Vincent'],W:['Walter','Willow'],Y:['Yvonne','Yusuf'],Z:['Zachary'] },
    animal: { A:['ape','alpaca'],B:['badger','buffalo'],C:['cheetah','crocodile'],D:['donkey','deer'],E:['eagle','eel'],F:['falcon','frog'],G:['goat','gazelle'],H:['hamster','hedgehog'],I:['insect'],J:['jellyfish','jackal'],K:['kingfisher'],L:['leopard','llama'],M:['mole','moose'],N:['narwhal','nightingale'],O:['octopus','orangutan'],P:['penguin','pig'],R:['raccoon','rat'],S:['snake','swan'],T:['toucan','turkey'],U:['urchin'],V:['vole'],W:['wombat','weasel'],Y:['yellowhammer'],Z:['zebu'] },
    plant: { A:['acacia','azalea'],B:['bamboo','begonia'],C:['clover','chamomile'],D:['dandelion','date palm'],E:['elder','elm'],F:['fuchsia','fennel'],G:['gardenia','ginger'],H:['hazel','holly'],I:['ice plant'],J:['juniper'],K:['kiwi'],L:['laurel','lotus'],M:['magnolia','moss'],N:['nasturtium','nutmeg'],O:['olive','oregano'],P:['pine','parsley'],R:['rhododendron','rye'],S:['spruce','sorrel'],T:['tea','tomato'],U:['umbrella tree'],V:['verbena'],W:['wheat','walnut'],Y:['yew'],Z:['zucchini'] },
    thing: { A:['armchair','alarm'],B:['bag','blanket'],C:['camera','candle'],D:['dictionary','drum'],E:['eraser','earring'],F:['fan','flashlight'],G:['guitar','glasses'],H:['helmet','hanger'],I:['ink','icebox'],J:['jacket','jug'],K:['knife','keyboard'],L:['laptop','lock'],M:['mattress','map'],N:['newspaper','necklace'],O:['ornament','outlet'],P:['plate','pillow'],R:['rope','ring'],S:['shelf','scissors'],T:['towel','toaster'],U:['uniform','utensil'],V:['vacuum'],W:['window','wheel'],Y:['yo-yo'],Z:['zither'] }
  },
  ru: {
    country: { А:['Албания','Австралия'],Б:['Болгария','Багамы'],В:['Венесуэла'],Г:['Грузия','Гана'],Д:['Доминикана'],И:['Индонезия','Иран','Ирландия'],К:['Казахстан','Кения','Куба'],М:['Марокко','Малайзия'],Н:['Нидерланды','Нигерия'],П:['Перу','Пакистан'],Р:['Руанда'],С:['Сингапур','Словения','Судан'],Т:['Тунис','Танзания'],Ф:['Филиппины'],Я:['Ямайка'] },
    city: { А:['Анкара','Атланта'],Б:['Барселона','Бостон'],В:['Ванкувер','Венеция'],Г:['Глазго','Генуя'],Д:['Дели','Даллас'],И:['Инсбрук','Стамбул'],К:['Каир','Копенгаген'],М:['Милан','Монреаль'],Н:['Найроби','Нью-Йорк'],П:['Пекин','Порту'],Р:['Роттердам','Рейкьявик'],С:['Стокгольм','Сингапур'],Т:['Таллин','Тбилиси'],Ф:['Франкфурт'],Я:['Ялта'] },
    name: { А:['Алиса','Артём'],Б:['Богдан','Беата'],В:['Валерия','Владимир'],Г:['Григорий','Грета'],Д:['Денис','Диана'],И:['Илья','Инна'],К:['Ксения','Константин'],М:['Михаил','Марина'],Н:['Нина','Никита'],П:['Пётр','Пелагея'],Р:['Рита','Руслан'],С:['Светлана','Степан'],Т:['Тамара','Тарас'],Ф:['Фаина','Филипп'],Я:['Яков','Ярослава'] },
    animal: { А:['аллигатор','альпака'],Б:['белка','бегемот'],В:['воробей','верблюд'],Г:['гусь','гиена'],Д:['дятел','дрозд'],И:['игуана','ибис'],К:['кролик','крокодил'],М:['морж','муравей'],Н:['нутрия','носуха'],П:['пингвин','пума'],Р:['рыба','росомаха'],С:['сова','сурок'],Т:['тукан','таракан'],Ф:['фазан'],Я:['ястреб','ящерица'] },
    plant: { А:['акация','азалия'],Б:['бамбук','бегония'],В:['виноград','вишня'],Г:['георгин','горох'],Д:['дельфиниум','донник'],И:['инжир','имбирь'],К:['каштан','кипарис'],М:['магнолия','малина'],Н:['настурция','нут'],П:['пальма','петрушка'],Р:['рожь','ревень'],С:['свёкла','смородина'],Т:['тополь','томат'],Ф:['фасоль','фуксия'],Я:['ясень','ячмень'] },
    thing: { А:['аптечка','антенна'],Б:['барабан','бумага'],В:['ведро','велосипед'],Г:['гармошка','гребень'],Д:['доска','дрель'],И:['инструмент','изолента'],К:['карандаш','ковёр'],М:['мяч','миксер'],Н:['наушники','нитка'],П:['плед','портфель'],Р:['рюкзак','ремень'],С:['сумка','свеча'],Т:['термос','тетрадь'],Ф:['фотоаппарат','фен'],Я:['якорь'] }
  },
  zh: {
    country: { B:['冰岛|bingdao','保加利亚|baojialiya'],D:['丹麦|danmai'],F:['芬兰|fenlan','菲律宾|feilvbin'],H:['哈萨克斯坦|hasakesitan'],J:['柬埔寨|jianpuzhai'],M:['马来西亚|malaixiya','摩洛哥|moluoge'],R:['瑞典|ruidian','瑞士|ruishi'],T:['土耳其|tuerqi','突尼斯|tunisi'],X:['希腊|xila','新西兰|xinxilan'],Y:['意大利|yidali','伊朗|yilang'],Z:['赞比亚|zanbiya'] },
    city: { B:['巴塞罗那|basailuona','柏林|bolin'],D:['东京|dongjing','都柏林|dubailin'],F:['佛罗伦萨|foluolunsa'],H:['汉堡|hanbao','赫尔辛基|heerxinji'],J:['京都|jingdu','加德满都|jiademandu'],M:['米兰|milan','墨尔本|moerben'],R:['日喀则|rikaze'],T:['台北|taibei'],X:['悉尼|xini','香港|xianggang'],Y:['雅典|yadian'],Z:['芝加哥|zhijiage','珠海|zhuhai'] },
    name: { B:['冰冰|bingbing'],D:['大伟|dawei'],F:['飞飞|feifei'],H:['红梅|hongmei'],J:['佳佳|jiajia'],M:['美玲|meiling'],R:['瑞雪|ruixue'],T:['涛涛|taotao'],X:['晓明|xiaoming'],Y:['一凡|yifan'],Z:['子涵|zihan'] },
    animal: { B:['斑马|banma','蝙蝠|bianfu'],D:['袋鼠|daishu','丹顶鹤|dandinghe'],F:['凤凰|fenghuang'],H:['河马|hema','狐狸|huli'],J:['鲸鱼|jingyu','金鱼|jinyu'],M:['马|ma','蜜蜂|mifeng'],R:['儒艮|rugeng'],T:['天鹅|tiane','田鼠|tianshu'],X:['小熊猫|xiaoxiongmao'],Y:['鸭子|yazi','鹰|ying'],Z:['章鱼|zhangyu','藏羚羊|zanglingyang'] },
    plant: { B:['薄荷|bohe','柏树|baishu'],D:['冬青|dongqing'],F:['番茄|fanqie'],H:['海棠|haitang','黄瓜|huanggua'],J:['金银花|jinyinhua','橘树|jushu'],M:['玫瑰|meigui','茉莉花|molihua'],R:['人参|renshen'],T:['藤|teng','铁树|tieshu'],X:['向日葵|xiangrikui'],Y:['杨树|yangshu','樱花|yinghua'],Z:['栀子花|zhizihua'] },
    thing: { B:['包|bao','笔|bi'],D:['电灯|diandeng','地图|ditu'],F:['飞机|feiji','饭盒|fanhe'],H:['盒子|hezi','画|hua'],J:['镜子|jingzi','家具|jiaju'],M:['帽子|maozi','毛巾|maojin'],R:['软件|ruanjian'],T:['头盔|toukui','梯子|tizi'],X:['相机|xiangji','信封|xinfeng'],Y:['眼镜|yanjing','钥匙|yaoshi'],Z:['钟|zhong','纸|zhi'] }
  }
}
